version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  raxmatjon0525
      POSTGRES_DB: nestUser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
