# services:
#   backend:
#     image: qazo-namoz-image:latest
#     container_name: qazo-namoz
#     ports:
#       - 3000:3000
#     environment:
#       - NODE_ENV=${NODE_ENV}
#       - DATABASE_URL=${DATABASE_URL}
#       - JWT_SECRET=${JWT_SECRET}
#       - NODE_ENV =production
  
version: "3.9"
services:
  backend:
    image: qazo-namoz-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qazo-namoz
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_AT_SECRET: ${JWT_AT_SECRET}
      JWT_RT_SECRET: ${JWT_RT_SECRET}
    networks:
      - app-network
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
   
networks:
  app-network:
    driver: bridge



# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: production
#     volumes:
#       - .:/app
#     restart: always
