# This is Docker Compose file for a Node.js application with a PostgreSQL database.
  
version: "3.9"
services:
  backend:
    image: qazo-namoz-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qazo-namoz
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_AT_SECRET: ${JWT_AT_SECRET}
      JWT_RT_SECRET: ${JWT_RT_SECRET}
    networks:
      - app-network
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
   
networks:
  app-network:
    driver: bridge

