services:
  backend:
    image: qazo-namoz-image:latest
    container_name: qazo-namoz
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
  


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: production
#     volumes:
#       - .:/app
#     restart: always
